name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  run-tests:

    runs-on: ubuntu-latest
    
    steps:

    - uses: actions/checkout@v3

    - name: build tests with clean install
      run: npm ci

    - name: run tests
      run: npm run tests